### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by danielsunnerberg**
Ran tests and tested manually in our code base and auto login functionality worked as expected.

### CODE REVIEW

**Comment by jmikola** [comment]
There is a test failure related to AuthenticationManagerInterface in the following CI build: https://github.com/jmikola/AutoLogin/actions/runs/4224927343/jobs/7366816906#step:7:22

A spent a few minutes digging into Symfony's git history and I believe this is related to the removal of deprecated APIs in https://github.com/symfony/symfony/pull/41613. The CI error above is caused by attempting to mock a non-existent class in AutoLoginListenerTest, but I expect changes will also be required in the AutoLoginListener class itself.

I have not been following changes to Symfony's Security component, but https://github.com/symfony/symfony/pull/33558 may be relevant (also came up while digging through git history).

**Comment by danielsunnerberg** [comment]
My apologies, I failed to run the tests using all versions of PHP. We chose to migrate our project to the [Symfony native implementation of auto login URLs](https://symfony.com/doc/current/security/login_link.html). Thank you for this project, it filled an important gap in Symfony's offerings.

**Comment by jmikola** [comment]
Thanks for alerting me to the existence of that feature. It looks like it was [introduced in 5.2](https://symfony.com/blog/new-in-symfony-5-2-login-links).

I think the best course of action would be to deprecate this library (and the [related bundle](https://github.com/jmikola/JmikolaAutoLoginBundle)) and update the README to point folks to the [LoginLink](https://symfony.com/doc/current/security/login_link.html) functionality in the Security component.

**Comment by danielsunnerberg** [comment]
> I think the best course of action would be to deprecate this library (and the [related bundle](https://github.com/jmikola/JmikolaAutoLoginBundle)) and update the README to point folks to the [LoginLink](https://symfony.com/doc/current/security/login_link.html) functionality in the Security component.

I agree. Do you want me to submit a PR to update the README?

**Comment by jmikola** [comment]
> Do you want me to submit a PR to update the README?

No worries. I can do so before [archiving](https://github.blog/2017-11-08-archiving-repositories/) both repositories and will aim to do so later this week.

**Pull request closed without merging**
